import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Download, Edit2, Share2, ArrowLeft, FileText } from 'lucide-react';

const renderValue = (value) => {
    if (Array.isArray(value)) {
        return (
            <ul className="list-disc list-inside space-y-1.5">
                {value.map((item, i) => (
                    <li key={i} className="text-gray-700 leading-relaxed">{item}</li>
                ))}
            </ul>
        );
    }
    if (typeof value === 'object' && value !== null) {
        return <pre className="text-sm bg-gray-50 border border-gray-200 rounded-lg p-4 overflow-auto">{JSON.stringify(value, null, 2)}</pre>;
    }
    return <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{String(value)}</p>;
};

const sectionLabel = (key) =>
    key.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').replace(/^\w/, c => c.toUpperCase());

const Preview = () => {
    const { state } = useLocation();
    const navigate = useNavigate();

    const generatedData = state?.generatedData;
    const title = state?.title || 'Generated Lab Manual';
    const formatSchema = state?.formatSchema;

    if (!generatedData) {
        return (
            <div className="flex flex-col items-center justify-center h-full text-center space-y-4 py-24">
                <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center">
                    <FileText size={32} className="text-gray-400" />
                </div>
                <h2 className="text-2xl font-bold text-gray-900">No Manual Loaded</h2>
                <p className="text-gray-500">Generate a lab manual first using the AI Generator.</p>
                <button className="btn-primary mt-2" onClick={() => navigate('/generator')}>Go to Generator</button>
            </div>
        );
    }

    // Determine section order: from formatSchema (PDF-detected) or fall back to object keys
    const sections = formatSchema?.sections
        ? formatSchema.sections.map(s => ({ key: s.key, label: s.label }))
        : Object.keys(generatedData).map(k => ({ key: k, label: sectionLabel(k) }));

    return (
        <div className="animate-fade-in w-full max-w-5xl mx-auto space-y-6">

            {/* ── Toolbar ── */}
            <div className="flex justify-between items-center">
                <div className="flex items-center gap-3">
                    <button className="btn-secondary !py-2 !px-3 flex items-center gap-2 text-sm" onClick={() => navigate('/generator')}>
                        <ArrowLeft size={16} /> Back
                    </button>
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
                        {formatSchema && <p className="text-xs text-green-600 font-medium flex items-center gap-1">✓ Generated using detected PDF format</p>}
                    </div>
                </div>
                <div className="flex gap-3">
                    <button className="btn-secondary flex items-center gap-2 text-sm"><Share2 size={16} /> Share</button>
                    <button className="btn-secondary flex items-center gap-2 text-sm"><Edit2 size={16} /> Edit</button>
                    <button className="btn-primary flex items-center gap-2 shadow-lg shadow-primary-500/30"><Download size={18} /> Download PDF</button>
                </div>
            </div>

            {/* ── Document ── */}
            <div className="bg-white border border-gray-200 shadow-xl rounded-xl overflow-hidden">
                {/* Document Header */}
                <div className="bg-gradient-to-r from-primary-700 to-primary-500 p-10 text-white text-center">
                    <p className="text-primary-200 uppercase tracking-widest text-xs mb-2 font-semibold">Laboratory Manual</p>
                    <h1 className="text-3xl font-bold">{title}</h1>
                    <p className="text-primary-200 mt-3 text-sm">Generated by LabGen AI • {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                </div>

                {/* Document Body */}
                <div className="divide-y divide-gray-100">
                    {sections.map(({ key, label }, i) => {
                        const value = generatedData[key];
                        if (!value) return null;

                        return (
                            <div key={key} className="p-8 hover:bg-gray-50/60 transition-colors group">
                                <div className="flex items-baseline gap-3 mb-4">
                                    <span className="text-2xl font-bold text-primary-200">{String(i + 1).padStart(2, '0')}</span>
                                    <h2 className="text-xl font-bold text-gray-900">{label}</h2>
                                </div>
                                <div className="ml-10">
                                    {renderValue(value)}
                                </div>
                            </div>
                        );
                    })}
                </div>

                {/* Footer */}
                <div className="border-t border-gray-100 p-6 bg-gray-50 text-center text-xs text-gray-400">
                    Generated with LabGen AI — Powered by Google Gemini
                </div>
            </div>

        </div>
    );
};

export default Preview;
